# Generated by Django 3.1.5 on 2021-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
